# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ColorCloudZoneIOSProjectV1.0' do
pod 'AVOSCloud'
end

target 'ColorCloudZoneIOSProjectV1.0Tests' do

end

